global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'odin'
          # nodename: 'odin'
      - targets: ['192.168.1.15:9100']
        labels:
          instance: 'loki'
          # nodename: 'loki'
      - targets: ['45.12.139.240:9100']
        labels:
          instance: 'vm-1'
          # nodename: 'vm-1'
      - targets: [ '45.136.58.233:9100' ]
        labels:
          instance: 'vm-2'
          # nodename: 'vm-2'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['inf-cadvisor:8080']
        labels:
          instance: 'odin'
      - targets: ['192.168.1.15:8080']
        labels:
          instance: 'loki'

  - job_name: 'redpanda-connect'
    static_configs:
      - targets: ['192.168.1.15:34195']
        labels:
          instance: 'loki'
